"""
registry.py — Registro central de todas as APIs do OpenClaw.
Adicionar uma nova API = adicionar um bloco neste arquivo.
"""

API_REGISTRY = {

    # ════════════════════════════════════════════════════
    # CEX — CORRETORAS CENTRALIZADAS
    # ════════════════════════════════════════════════════

    "binance": {
        "module":        "api_gateway.cex.binance",
        "class":         "BinanceClient",
        "display_name":  "Binance",
        "category":      "cex",
        "free":          True,
        "key_required":  False,
        "key_optional":  True,
        "rate_limit":    1200,
        "rate_limit_key": 6000,
        "base_url": {
            "spot":         "https://api.binance.com/api/v3",
            "futures":      "https://fapi.binance.com/fapi/v1",
            "futures_data": "https://fapi.binance.com/futures/data",
            "delivery":     "https://dapi.binance.com/dapi/v1",
        },
        "supports": [
            "price", "ohlcv", "orderbook", "trades",
            "funding_rate", "open_interest", "long_short_ratio",
            "liquidations", "taker_buy_sell", "mark_price",
        ],
        "chains": ["BSC"],
        "docs": "https://binance-docs.github.io/apidocs/futures/en/",
        "endpoints": {
            "ping":              "/ping",
            "price":             "/ticker/price",
            "funding_rate":      "/premiumIndex",
            "funding_history":   "/fundingRate",
            "open_interest":     "/openInterest",
            "oi_history":        "/openInterestHist",
            "ls_ratio_account":  "/topLongShortAccountRatio",
            "ls_ratio_position": "/topLongShortPositionRatio",
            "ls_ratio_global":   "/globalLongShortAccountRatio",
            "liquidations":      "/forceOrders",
            "klines":            "/klines",
            "depth":             "/depth",
            "ticker_24h":        "/ticker/24hr",
            "exchange_info":     "/exchangeInfo",
        },
    },

    "bybit": {
        "module":       "api_gateway.cex.bybit",
        "class":        "BybitClient",
        "display_name": "Bybit",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   120,
        "base_url": {
            "v5":   "https://api.bybit.com/v5",
            "spot": "https://api.bybit.com/v5/market",
        },
        "supports": [
            "price", "ohlcv", "funding_rate", "open_interest",
            "long_short_ratio", "liquidations", "insurance_fund",
        ],
        "docs": "https://bybit-exchange.github.io/docs/v5/intro",
        "endpoints": {
            "ping":            "/market/time",
            "tickers":         "/market/tickers",
            "funding_history": "/market/funding/history",
            "open_interest":   "/market/open-interest",
            "ls_ratio":        "/market/account-ratio",
            "klines":          "/market/kline",
            "recent_trades":   "/market/recent-trade",
            "instruments":     "/market/instruments-info",
        },
    },

    "okx": {
        "module":       "api_gateway.cex.okx",
        "class":        "OKXClient",
        "display_name": "OKX",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   60,
        "base_url": {
            "public": "https://www.okx.com/api/v5/public",
            "market": "https://www.okx.com/api/v5/market",
        },
        "supports": [
            "price", "ohlcv", "funding_rate", "open_interest",
            "liquidations", "mark_price", "index_price",
        ],
        "docs": "https://www.okx.com/docs-v5/en/",
        "endpoints": {
            "funding_rate":    "/funding-rate",
            "funding_history": "/funding-rate-history",
            "open_interest":   "/open-interest",
            "liquidation":     "/liquidation-orders",
            "tickers":         "/tickers",
            "candles":         "/candles",
            "instruments":     "/instruments",
            "mark_price":      "/mark-price",
        },
    },

    "coinbase": {
        "module":       "api_gateway.cex.coinbase",
        "class":        "CoinbaseClient",
        "display_name": "Coinbase Advanced",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "v3":       "https://api.coinbase.com/api/v3/brokerage",
            "exchange": "https://api.exchange.coinbase.com",
        },
        "supports": ["price", "ohlcv", "orderbook", "trades"],
        "docs": "https://docs.cdp.coinbase.com/advanced-trade/docs/welcome",
        "endpoints": {
            "products":  "/products",
            "candles":   "/products/{product_id}/candles",
            "ticker":    "/products/{product_id}/ticker",
            "orderbook": "/products/{product_id}/book",
            "trades":    "/products/{product_id}/trades",
        },
    },

    "kraken": {
        "module":       "api_gateway.cex.kraken",
        "class":        "KrakenClient",
        "display_name": "Kraken",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   60,
        "base_url": {
            "public":  "https://api.kraken.com/0/public",
            "futures": "https://futures.kraken.com/derivatives/api/v3",
        },
        "supports": [
            "price", "ohlcv", "orderbook", "funding_rate", "open_interest",
        ],
        "docs": "https://docs.kraken.com/rest/",
        "endpoints": {
            "ticker":        "/Ticker",
            "ohlc":          "/OHLC",
            "orderbook":     "/Depth",
            "trades":        "/Trades",
            "funding_rate":  "/tickers",
            "open_interest": "/openinterests",
            "instruments":   "/instruments",
        },
    },

    "gate": {
        "module":       "api_gateway.cex.gate",
        "class":        "GateClient",
        "display_name": "Gate.io",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   900,
        "base_url": {
            "spot":    "https://api.gateio.ws/api/v4/spot",
            "futures": "https://api.gateio.ws/api/v4/futures/usdt",
        },
        "supports": [
            "price", "ohlcv", "funding_rate", "open_interest",
            "long_short_ratio",
        ],
        "docs": "https://www.gate.io/docs/developers/apiv4/",
        "endpoints": {
            "tickers":       "/tickers",
            "funding_rate":  "/funding_rate",
            "open_interest": "/contracts",
            "candlesticks":  "/candlesticks",
            "order_book":    "/order_book",
            "liquidates":    "/liquidates",
        },
    },

    "mexc": {
        "module":       "api_gateway.cex.mexc",
        "class":        "MEXCClient",
        "display_name": "MEXC",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   240,
        "base_url": {
            "spot":    "https://api.mexc.com/api/v3",
            "futures": "https://contract.mexc.com/api/v1/contract",
        },
        "supports": ["price", "ohlcv", "funding_rate", "open_interest"],
        "docs": "https://mexcdevelop.github.io/apidocs/contract_v1_en/",
        "endpoints": {
            "ping":          "/ping",
            "ticker":        "/ticker/price",
            "funding_rate":  "/funding_rate",
            "open_interest": "/open_interest",
            "kline":         "/kline",
        },
    },

    "bitget": {
        "module":       "api_gateway.cex.bitget",
        "class":        "BitgetClient",
        "display_name": "Bitget",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   120,
        "base_url": {
            "mix": "https://api.bitget.com/api/mix/v1",
            "v2":  "https://api.bitget.com/api/v2/mix",
        },
        "supports": [
            "price", "ohlcv", "funding_rate", "open_interest",
            "long_short_ratio",
        ],
        "docs": "https://www.bitget.com/api-doc/contract/intro",
        "endpoints": {
            "tickers":       "/market/tickers",
            "funding_time":  "/market/current-fund-rate",
            "history_fund":  "/market/history-fund-rate",
            "open_interest": "/market/open-interest",
            "ls_ratio":      "/market/long-short-ratio",
            "candles":       "/market/candles",
        },
    },

    "htx": {
        "module":       "api_gateway.cex.htx",
        "class":        "HTXClient",
        "display_name": "HTX (Huobi)",
        "category":     "cex",
        "free":         True,
        "key_required": False,
        "rate_limit":   100,
        "base_url": {
            "market":  "https://api.huobi.pro/market",
            "futures": "https://api.hbdm.com/linear-swap-ex/market",
        },
        "supports": ["price", "ohlcv", "funding_rate", "open_interest"],
        "docs": "https://huobiapi.github.io/docs/usdt_swap/v1/en/",
        "endpoints": {
            "funding_rate":  "/swap-funding-rate",
            "open_interest": "/swap-open-interest",
            "kline":         "/history/index/kline",
            "detail":        "/detail/merged",
        },
    },

    # ════════════════════════════════════════════════════
    # DEX — CORRETORAS DESCENTRALIZADAS
    # ════════════════════════════════════════════════════

    "uniswap_v3": {
        "module":       "api_gateway.dex.uniswap_v3",
        "class":        "UniswapV3Client",
        "display_name": "Uniswap V3",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_CL",
        "chains":       ["Ethereum", "Arbitrum", "Optimism", "Base", "Polygon"],
        "rate_limit":   30,
        "base_url": {
            "ethereum": "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3",
            "arbitrum": "https://api.thegraph.com/subgraphs/name/ianlapham/arbitrum-minimal",
            "optimism": "https://api.thegraph.com/subgraphs/name/ianlapham/optimism-post-regenesis",
            "base":     "https://api.studio.thegraph.com/query/48211/uniswap-v3-base/version/latest",
            "polygon":  "https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon",
        },
        "supports": ["pools", "tvl", "volume", "fees", "apr", "token_price", "liquidity_positions"],
        "interface": "graphql",
        "docs": "https://docs.uniswap.org/api/subgraph/overview",
    },

    "uniswap_v2": {
        "module":       "api_gateway.dex.uniswap_v2",
        "class":        "UniswapV2Client",
        "display_name": "Uniswap V2",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM",
        "chains":       ["Ethereum"],
        "rate_limit":   30,
        "base_url": {
            "ethereum": "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2",
        },
        "supports": ["pools", "tvl", "volume", "fees"],
        "interface": "graphql",
        "docs": "https://docs.uniswap.org/contracts/v2/overview",
    },

    "aerodrome": {
        "module":       "api_gateway.dex.aerodrome",
        "class":        "AerodromeClient",
        "display_name": "Aerodrome Finance",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_VE",
        "chains":       ["Base"],
        "rate_limit":   60,
        "base_url": {
            "api":      "https://api.aerodrome.finance/api/v1",
            "subgraph": "https://api.studio.thegraph.com/query/67213/aerodrome/version/latest",
        },
        "supports": ["pools", "tvl", "volume", "apr", "emissions", "gauges"],
        "interface": "rest+graphql",
        "docs": "https://aerodrome.finance/docs",
        "endpoints": {
            "pools":   "/pools",
            "pairs":   "/pairs",
            "gauges":  "/gauges",
            "rewards": "/rewards",
        },
    },

    "velodrome": {
        "module":       "api_gateway.dex.velodrome",
        "class":        "VelodromeClient",
        "display_name": "Velodrome Finance",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_VE",
        "chains":       ["Optimism"],
        "rate_limit":   60,
        "base_url": {
            "api":      "https://api.velodrome.finance/api/v1",
            "subgraph": "https://api.thegraph.com/subgraphs/name/velodrome-finance/velodrome-v2",
        },
        "supports": ["pools", "tvl", "volume", "apr", "emissions"],
        "interface": "rest+graphql",
        "docs": "https://docs.velodrome.finance/",
    },

    "curve": {
        "module":       "api_gateway.dex.curve",
        "class":        "CurveClient",
        "display_name": "Curve Finance",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_STABLE",
        "chains": ["Ethereum", "Arbitrum", "Optimism", "Base", "Polygon", "Avalanche", "BSC"],
        "rate_limit":   60,
        "base_url": {
            "api": "https://api.curve.fi/api",
        },
        "supports": ["pools", "tvl", "volume", "apr", "base_apy", "crv_apy"],
        "interface": "rest",
        "docs": "https://docs.curve.fi/",
        "endpoints": {
            "pools":     "/getPools/{chain}/main",
            "factory":   "/getPools/{chain}/factory",
            "volumes":   "/getVolumes/{chain}",
            "gauges":    "/getGauges",
            "total_tvl": "/getTVLData",
        },
    },

    "balancer": {
        "module":       "api_gateway.dex.balancer",
        "class":        "BalancerClient",
        "display_name": "Balancer V2",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_WEIGHTED",
        "chains":       ["Ethereum", "Arbitrum", "Polygon", "Base", "Optimism"],
        "rate_limit":   30,
        "base_url": {
            "ethereum": "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2",
            "arbitrum": "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-arbitrum-v2",
            "polygon":  "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-v2",
        },
        "supports": ["pools", "tvl", "volume", "apr", "weighted_pools"],
        "interface": "graphql",
        "docs": "https://docs.balancer.fi/",
    },

    "pancakeswap": {
        "module":       "api_gateway.dex.pancakeswap",
        "class":        "PancakeSwapClient",
        "display_name": "PancakeSwap V3",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_CL",
        "chains":       ["BSC", "Ethereum", "Arbitrum", "Base"],
        "rate_limit":   60,
        "base_url": {
            "bsc":      "https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-bsc",
            "ethereum": "https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-eth",
            "api":      "https://api.pancakeswap.info/api/v2",
        },
        "supports": ["pools", "tvl", "volume", "apr", "cake_rewards"],
        "interface": "graphql+rest",
        "docs": "https://docs.pancakeswap.finance/",
    },

    "sushiswap": {
        "module":       "api_gateway.dex.sushiswap",
        "class":        "SushiSwapClient",
        "display_name": "SushiSwap",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM",
        "chains": ["Ethereum", "Arbitrum", "Polygon", "Optimism", "Base", "Avalanche", "BSC"],
        "rate_limit":   30,
        "base_url": {
            "v3_api": "https://api.sushi.com/pool/v2",
        },
        "supports": ["pools", "tvl", "volume", "apr"],
        "interface": "rest",
        "docs": "https://dev.sushi.com/",
        "endpoints": {
            "pools":  "/",
            "pool":   "/{chain}/{address}",
            "tokens": "/tokens",
        },
    },

    "raydium": {
        "module":       "api_gateway.dex.raydium",
        "class":        "RaydiumClient",
        "display_name": "Raydium (Solana)",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_CL",
        "chains":       ["Solana"],
        "rate_limit":   60,
        "base_url": {
            "api": "https://api.raydium.io/v2",
        },
        "supports": ["pools", "tvl", "volume", "apr"],
        "interface": "rest",
        "docs": "https://docs.raydium.io/",
        "endpoints": {
            "pairs": "/main/pairs",
            "info":  "/main/info",
            "farm":  "/main/farm/info",
            "clmm":  "/main/clmm-pool/list",
        },
    },

    "orca": {
        "module":       "api_gateway.dex.orca",
        "class":        "OrcaClient",
        "display_name": "Orca (Solana)",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "protocol":     "AMM_CL",
        "chains":       ["Solana"],
        "rate_limit":   30,
        "base_url": {
            "api": "https://api.orca.so",
        },
        "supports": ["pools", "tvl", "volume", "apr"],
        "interface": "rest",
        "docs": "https://docs.orca.so/",
        "endpoints": {
            "pools":  "/v1/whirlpool/list",
            "pool":   "/v1/whirlpool/{address}",
            "tokens": "/v1/token/list",
        },
    },

    "jupiter": {
        "module":       "api_gateway.dex.jupiter",
        "class":        "JupiterClient",
        "display_name": "Jupiter (Solana Aggregator)",
        "category":     "dex",
        "free":         True,
        "key_required": False,
        "chains":       ["Solana"],
        "rate_limit":   60,
        "base_url": {
            "price":  "https://price.jup.ag/v6",
            "quote":  "https://quote-api.jup.ag/v6",
            "tokens": "https://token.jup.ag/all",
        },
        "supports": ["price", "swap_routes", "token_list"],
        "interface": "rest",
        "docs": "https://dev.jup.ag/",
        "endpoints": {
            "price":  "/price",
            "quote":  "/quote",
        },
    },

    # ════════════════════════════════════════════════════
    # AGREGADORES MULTI-FONTE
    # ════════════════════════════════════════════════════

    "defillama": {
        "module":       "api_gateway.aggregators.defillama",
        "class":        "DefiLlamaClient",
        "display_name": "DefiLlama",
        "category":     "aggregators",
        "free":         True,
        "key_required": False,
        "rate_limit":   300,
        "base_url": {
            "tvl":     "https://api.llama.fi",
            "yields":  "https://yields.llama.fi",
            "coins":   "https://coins.llama.fi",
            "stables": "https://stablecoins.llama.fi",
            "bridges": "https://bridges.llama.fi",
        },
        "supports": [
            "tvl", "pools", "yields", "apr", "apy",
            "protocol_tvl", "chain_tvl", "stablecoins",
            "bridges", "token_price", "historical_price",
        ],
        "chains": "ALL",
        "interface": "rest",
        "docs": "https://defillama.com/docs/api",
        "endpoints": {
            "pools":       "/pools",
            "pools_chart": "/chart/{pool}",
            "protocols":   "/protocols",
            "protocol":    "/protocol/{name}",
            "chains":      "/chains",
            "tvl":         "/tvl/{protocol}",
            "token_price": "/prices/current/{coins}",
            "historical":  "/prices/historical/{ts}/{coins}",
            "stablecoins": "/stablecoins",
            "bridges":     "/bridges",
        },
    },

    "coingecko": {
        "module":       "api_gateway.aggregators.coingecko",
        "class":        "CoinGeckoClient",
        "display_name": "CoinGecko",
        "category":     "aggregators",
        "free":         True,
        "key_required": False,
        "key_optional": True,
        "rate_limit":   30,
        "rate_limit_key": 500,
        "base_url": {
            "v3":  "https://api.coingecko.com/api/v3",
            "pro": "https://pro-api.coingecko.com/api/v3",
        },
        "supports": [
            "price", "market_cap", "volume", "ohlcv",
            "global_market", "btc_dominance", "trending",
            "token_info", "exchange_list", "categories",
        ],
        "chains": "ALL",
        "interface": "rest",
        "docs": "https://docs.coingecko.com/",
        "endpoints": {
            "price":       "/simple/price",
            "token_price": "/simple/token_price/{platform}",
            "global":      "/global",
            "trending":    "/search/trending",
            "markets":     "/coins/markets",
            "coin":        "/coins/{id}",
            "ohlcv":       "/coins/{id}/ohlc",
            "history":     "/coins/{id}/history",
            "exchanges":   "/exchanges",
            "categories":  "/coins/categories",
        },
    },

    "coinmarketcap": {
        "module":       "api_gateway.aggregators.coinmarketcap",
        "class":        "CoinMarketCapClient",
        "display_name": "CoinMarketCap",
        "category":     "aggregators",
        "free":         True,
        "key_required": True,
        "key_free_url": "https://pro.coinmarketcap.com/signup",
        "rate_limit":   30,
        "base_url": {
            "v1": "https://pro-api.coinmarketcap.com/v1",
            "v2": "https://pro-api.coinmarketcap.com/v2",
            "v3": "https://pro-api.coinmarketcap.com/v3",
        },
        "supports": [
            "price", "market_cap", "volume", "rankings",
            "global_metrics", "fear_greed",
        ],
        "auth_header": "X-CMC_PRO_API_KEY",
        "interface": "rest",
        "docs": "https://coinmarketcap.com/api/documentation/v1/",
        "endpoints": {
            "listings":   "/cryptocurrency/listings/latest",
            "quotes":     "/cryptocurrency/quotes/latest",
            "global":     "/global-metrics/quotes/latest",
            "fear_greed": "/fear-and-greed/latest",
            "categories": "/cryptocurrency/categories",
            "trending":   "/cryptocurrency/trending/latest",
        },
    },

    "dexscreener": {
        "module":       "api_gateway.aggregators.dexscreener",
        "class":        "DexScreenerClient",
        "display_name": "DexScreener",
        "category":     "aggregators",
        "free":         True,
        "key_required": False,
        "rate_limit":   300,
        "base_url": {
            "api": "https://api.dexscreener.com/latest/dex",
        },
        "supports": [
            "pairs", "token_pairs", "search_pairs",
            "price", "volume", "liquidity", "price_change",
        ],
        "chains": "ALL",
        "interface": "rest",
        "docs": "https://docs.dexscreener.com/api/reference",
        "endpoints": {
            "pairs":     "/pairs/{chain}/{pair}",
            "token":     "/tokens/{addresses}",
            "search":    "/search/?q={query}",
            "new_pairs": "/pairs/{chain}/new",
            "boosted":   "/tokens/boosted",
        },
    },

    "coinglass": {
        "module":       "api_gateway.aggregators.coinglass",
        "class":        "CoinGlassClient",
        "display_name": "CoinGlass",
        "category":     "aggregators",
        "free":         True,
        "key_required": False,
        "key_optional": True,
        "rate_limit":   30,
        "base_url": {
            "public": "https://open-api.coinglass.com/public/futures",
            "v3":     "https://open-api.coinglass.com/api/futures",
        },
        "supports": [
            "open_interest", "liquidations", "long_short_ratio",
            "funding_rate", "options_data", "fear_greed",
            "exchange_inflow_outflow",
        ],
        "interface": "rest",
        "docs": "https://coinglass.readme.io/",
        "endpoints": {
            "funding_rate":      "/funding-rate",
            "open_interest":     "/openInterest",
            "liquidation_chart": "/liquidation/chart",
            "ls_ratio":          "/longShortRatio",
            "fear_greed":        "/fearAndGreedIndex",
            "exchange_stat":     "/stat",
        },
    },

    "the_graph": {
        "module":       "api_gateway.aggregators.the_graph",
        "class":        "TheGraphClient",
        "display_name": "The Graph",
        "category":     "aggregators",
        "free":         True,
        "key_required": False,
        "key_optional": True,
        "rate_limit":   30,
        "base_url": {
            "hosted":  "https://api.thegraph.com/subgraphs/name",
            "gateway": "https://gateway.thegraph.com/api",
            "studio":  "https://api.studio.thegraph.com/query",
        },
        "supports": [
            "any_subgraph", "custom_queries",
            "uniswap_v3", "aave", "compound", "synthetix",
        ],
        "interface": "graphql",
        "docs": "https://thegraph.com/docs/",
        "subgraphs": {
            "uniswap_v3_eth": "uniswap/uniswap-v3",
            "uniswap_v3_arb": "ianlapham/arbitrum-minimal",
            "aave_v3_eth":    "aave/protocol-v3",
            "compound_v3":    "messari/compound-v3-ethereum",
            "balancer_eth":   "balancer-labs/balancer-v2",
            "curve_eth":      "messari/curve-finance-ethereum",
            "gmx_arb":        "gmx-io/gmx-stats",
        },
    },

    "dextools": {
        "module":       "api_gateway.aggregators.dextools",
        "class":        "DexToolsClient",
        "display_name": "DexTools",
        "category":     "aggregators",
        "free":         True,
        "key_required": True,
        "key_free_url": "https://developer.dextools.io/",
        "rate_limit":   30,
        "base_url": {
            "v2": "https://public-api.dextools.io/trial/v2",
        },
        "supports": [
            "pool_info", "price", "ohlcv", "liquidity",
            "token_audit", "pair_explorer",
        ],
        "auth_header": "X-API-Key",
        "interface": "rest",
        "docs": "https://developer.dextools.io/docs",
        "endpoints": {
            "pool":      "/pool/{chain}/{address}",
            "token":     "/token/{chain}/{address}",
            "price":     "/token/{chain}/{address}/price",
            "ohlcv":     "/pool/{chain}/{address}/ohlcv",
            "liquidity": "/pool/{chain}/{address}/liquidity",
            "audit":     "/token/{chain}/{address}/audit",
        },
    },

    # ════════════════════════════════════════════════════
    # ON-CHAIN — RPCs GRATUITOS
    # ════════════════════════════════════════════════════

    "ethereum_rpc": {
        "module":       "api_gateway.onchain.ethereum",
        "class":        "EthereumRPCClient",
        "display_name": "Ethereum RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "cloudflare": "https://cloudflare-eth.com",
            "ankr":       "https://rpc.ankr.com/eth",
            "llamarpc":   "https://eth.llamarpc.com",
            "publicnode": "https://ethereum-rpc.publicnode.com",
            "drpc":       "https://eth.drpc.org",
        },
        "supports": ["block_number", "balance", "transaction", "contract_call", "logs", "gas_price"],
        "interface": "json_rpc",
        "chain_id":  1,
    },

    "arbitrum_rpc": {
        "module":       "api_gateway.onchain.arbitrum",
        "class":        "ArbitrumRPCClient",
        "display_name": "Arbitrum One RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://arb1.arbitrum.io/rpc",
            "ankr":       "https://rpc.ankr.com/arbitrum",
            "llamarpc":   "https://arbitrum.llamarpc.com",
            "publicnode": "https://arbitrum-one-rpc.publicnode.com",
            "drpc":       "https://arbitrum.drpc.org",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  42161,
    },

    "base_rpc": {
        "module":       "api_gateway.onchain.base_chain",
        "class":        "BaseRPCClient",
        "display_name": "Base Chain RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://mainnet.base.org",
            "ankr":       "https://rpc.ankr.com/base",
            "llamarpc":   "https://base.llamarpc.com",
            "publicnode": "https://base-rpc.publicnode.com",
            "drpc":       "https://base.drpc.org",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  8453,
    },

    "optimism_rpc": {
        "module":       "api_gateway.onchain.optimism",
        "class":        "OptimismRPCClient",
        "display_name": "Optimism RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://mainnet.optimism.io",
            "ankr":       "https://rpc.ankr.com/optimism",
            "llamarpc":   "https://optimism.llamarpc.com",
            "publicnode": "https://optimism-rpc.publicnode.com",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  10,
    },

    "polygon_rpc": {
        "module":       "api_gateway.onchain.polygon",
        "class":        "PolygonRPCClient",
        "display_name": "Polygon RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://polygon-rpc.com",
            "ankr":       "https://rpc.ankr.com/polygon",
            "llamarpc":   "https://polygon.llamarpc.com",
            "publicnode": "https://polygon-bor-rpc.publicnode.com",
            "drpc":       "https://polygon.drpc.org",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  137,
    },

    "solana_rpc": {
        "module":       "api_gateway.onchain.solana",
        "class":        "SolanaRPCClient",
        "display_name": "Solana RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   60,
        "base_url": {
            "mainnet":    "https://api.mainnet-beta.solana.com",
            "ankr":       "https://rpc.ankr.com/solana",
            "publicnode": "https://solana-rpc.publicnode.com",
        },
        "supports": ["slot", "balance", "transaction", "account_info", "program_accounts"],
        "interface": "json_rpc",
        "chain_id":  "solana_mainnet",
    },

    "bsc_rpc": {
        "module":       "api_gateway.onchain.bsc",
        "class":        "BSCRPCClient",
        "display_name": "BNB Smart Chain RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://bsc-dataseed.binance.org",
            "ankr":       "https://rpc.ankr.com/bsc",
            "publicnode": "https://bsc-rpc.publicnode.com",
            "drpc":       "https://bsc.drpc.org",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  56,
    },

    "avalanche_rpc": {
        "module":       "api_gateway.onchain.avalanche",
        "class":        "AvalancheRPCClient",
        "display_name": "Avalanche C-Chain RPC",
        "category":     "onchain",
        "free":         True,
        "key_required": False,
        "rate_limit":   30,
        "base_url": {
            "official":   "https://api.avax.network/ext/bc/C/rpc",
            "ankr":       "https://rpc.ankr.com/avalanche",
            "publicnode": "https://avalanche-c-chain-rpc.publicnode.com",
            "drpc":       "https://avalanche.drpc.org",
        },
        "supports": ["block_number", "balance", "contract_call", "logs"],
        "interface": "json_rpc",
        "chain_id":  43114,
    },
}
